### ISSUE TITLE
Unable to run package in Linux Mint

### ISSUE THREAD

**Issue by karpo518** [zquestz/geoclue-tz#1]
I installed geoclue-tz on my Linux Mint Cinnamon 21.3,  but after installation I get an error:
```
$ geoclue-tz
geoclue-tz: command not found
```

installation log:
```
$ go install github.com/zquestz/geoclue-tz@latest
go: downloading github.com/zquestz/geoclue-tz v1.0.0
go: downloading github.com/zquestz/go-ucl v0.0.0-20220615095619-8a3686d7543a
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/spf13/pflag v1.0.5
```
go version:
```
$ go version
go version go1.23.2 linux/amd64
```
go env:
```
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/karpo518/YandexDisk/go/bin'
GOCACHE='/home/karpo518/.cache/go-build'
GOENV='/home/karpo518/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/karpo518/YandexDisk/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/karpo518/YandexDisk/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/karpo518/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build183472936=/tmp/go-build -gno-record-gcc-switches'

```

Package path:
/home/karpo518/YandexDisk/go/bin/geoclue-tz

**Comment by zquestz** [comment]
`go install` installs the binary into your $GOPATH which may not be setup by default in your $PATH.

Try just building the binary and copying to `/usr/bin`

```
cd geoclue-tz
go build .
sudo cp geoclue-tz /usr/bin
```

**Comment by zquestz** [comment]
You can get it to run from your installed location by adding your go/bin directory to your $PATH.

```
export PATH=/home/karpo518/YandexDisk/go/bin:$PATH
```

**Comment by karpo518** [comment]
Thanks for your reply. I don't understand what you mean by cd geoclue-tz because no such directory is created when the package is installed. Only file. I solved the initial problem and set up PATH correctly, but I'm still stuck.

```
$ go env
GO111MODULE=''
GOARCH='amd64'
GOBIN='/home/karpo518/go/bin'
GOCACHE='/home/karpo518/.cache/go-build'
GOENV='/home/karpo518/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/karpo518/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/karpo518/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/karpo518/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1583440530=/tmp/go-build -gno-record-gcc-switches'

$ echo "$PATH"
/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.local/bin:/home/karpo518/.nvm/versions/node/v20.8.0/bin:/home/karpo518/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/karpo518/.local/share/JetBrains/Toolbox/scripts___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh:/usr/local/go/bin:/usr/local/go/bin:/home/karpo518/.local/share/JetBrains/Toolbox/scripts___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh:/usr/local/go/bin:/usr/local/go/bin:/home/karpo518/.local/share/JetBrains/Toolbox/scripts___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh:/usr/local/go/bin:/usr/local/go/bin___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh:/usr/local/go/bin:/usr/local/go/bin___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh:/usr/local/go/bin:/usr/local/go/bin___MY_VMOPTIONS_SHELL_FILE=/home/karpo518/.jetbrains.vmoptions.sh:/home/karpo518/go/bin:/usr/local/go/bin:/usr/local/go/bin


$ go install github.com/zquestz/geoclue-tz@latest
$ geoclue-tz
[Error] Unable to write "/etc/geolocation": root access required
$ sudo geoclue-tz
sudo: geoclue-tz: команда не найдена
$ cd $HOME/go/bin/
$ ls -hl
summary 5,7M
-rwxrwxr-x 1 karpo518 karpo518 5,7M ноя  7 10:11 geoclue-tz
$ go build .
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by zquestz** [comment]
This is because unfortunately sudo doesn't preserve your PATH. =\

You have two options.

1. Run `sudo ./geoclue-tz` in $HOME/go/bin

```
cd $HOME/go/bin
sudo ./geoclue-tz
```

2. Copy the binary to `/usr/bin`.

```
cd $HOME/go/bin
sudo cp geoclue-tz /usr/bin/geoclue-tz
```

Then you can just run it normally with `sudo geoclue-tz`

Hope this helps.

**Comment by zquestz** [comment]
I updated README.md with better install directions. Hopefully it helps!

**Comment by karpo518** [comment]
Okay. I can run it by Option 1 or 2. But i dont understand, how it fix redshift problem. I came here from the topic =) https://forums.linuxmint.com/viewtopic.php?t=422300 

I got message:`Successfully updated "/etc/geolocation" with "Europe/Moscow" location`

But my redshift still doesn't work. And restart of redshift/OS does not help me

**Comment by zquestz** [comment]
Okay, so there are a few things to check, to make sure things are working correctly!

First run `/usr/lib/geoclue-2.0/demos/where-am-i`

This should output your coordinates, and makes sure that GeoClue itself is working correctly! If this errors out that means GeoClue isn't running on your machine, and it will need to be started! You can check GeoClue status with `sudo systemctl status geoclue`. This should show it active and running. If not, you can start it with `sudo systemctl start geoclue`.

Then, if geoclue is running and working, you want to make sure the geoclue agent is running, this is what RedShift talks to in order to connect to GeoClue! So run `ps aux | grep geoclue` and you should see `/usr/lib/geoclue-2.0/demos/agent` running. If not you must make sure that is started! Just start it with ` /usr/lib/geoclue-2.0/demos/agent &`. This will make sure it is started in the background.

Now, once all those things are going, then RedShift should be able to get your coordinates correctly. Most distros will make sure GeoClue is running with its agent, so technically everything I stated above should already be working!

Now, I personally use `redshift-gtk` which shows RedShift in my systray. If you click on the RedShift icon, and go to `Info` it should show something like:

![image](https://github.com/user-attachments/assets/eb324d28-2770-4064-828c-6794e8163a83)

This means RedShift is working as expected!

**Comment by karpo518** [comment]
> First run `/usr/lib/geoclue-2.0/demos/where-am-i`

There are no /usr/lib/geoclue* directories on my system
My redshift: window:
![screen1](https://github.com/user-attachments/assets/8da31552-2f7c-4ca7-b3d5-aec3f6f75196)

The error I get when I change any Redshift setting:
![screen2](https://github.com/user-attachments/assets/1f47d92a-ff1a-4577-bef6-a495b25c6509)

**Comment by zquestz** [comment]
Well it looks like you have a few issues.

1. RedShift doesn't work on Wayland =(
2. GeoClue isn't even installed on your machine, so that would need to be installed.

Luckily Linux Mint is integrating a Night Light feature right now. You will just need to be patient. https://blog.linuxmint.com/?p=4762
